CREATE TABLE Project (
id INTEGER NOT NULL PRIMARY KEY,
"uuid" TEXT NOT NULL UNIQUE,
"name" TEXT NOT NULL UNIQUE,
loc INTEGER NOT NULL,
"files" INTEGER NOT NULL,
created_at TEXT NOT NULL,
updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS butane_migrations (
"name" TEXT NOT NULL PRIMARY KEY
);
